#!/bin/bash

# Copy all remaining pages from backup to src
echo "Starting comprehensive page restoration..."

# List of directories to copy (excluding those already copied)
pages_to_copy=(
    "3d-visualization"
    "affiliate"
    "affiliates"
    "ai-optimization"
    "automation"
    "autopilot"
    "battery-optimization"
    "blog"
    "bms"
    "business-modeling"
    "button-audit"
    "canvas-test"
    "case-studies"
    "cfd-analysis"
    "climate-computers"
    "climate-tools"
    "collaboration-demo"
    "compare"
    "compliance-calendar"
    "consultations"
    "contact"
    "control-center"
    "credit-building"
    "credit-funding"
    "customer-success"
    "dashboard-demo-simple"
    "dashboard-demo"
    "dashboard-test"
    "dashboard-working"
    "debug-js"
    "debug"
    "demand-response"
    "demo-ai-design"
    "demo-sidebar"
    "demo"
    "developer-tools"
    "developer"
    "digital-twin"
    "disputes"
    "docs"
    "energy-dashboard"
    "energy-monitoring-test"
    "energy-monitoring"
    "energy-savings"
    "energy-setup"
    "enterprise"
    "equipment-board"
    "equipment"
    "expert-dashboard"
    "experts"
    "faq"
    "food-safety"
    "forgot-password"
    "get-started"
    "go"
    "gpu-raytracing"
    "growing"
    "help"
    "hyperspectral-integration"
    "hyperspectral"
    "insurance"
    "integration"
    "intelligence"
    "investment"
    "investor-portal"
    "investors"
    "ipm"
    "lease-vs-buy"
    "legal"
    "light-tools"
    "lighting-tools"
    "login"
    "maintenance-service"
    "mobile-dashboard"
    "mobile-designer"
    "multi-site"
    "onboarding"
    "partner-portal"
    "performance"
    "pid-control"
    "pilot-program"
    "plant-biology"
    "plant-monitoring"
    "portals"
    "presentation"
    "pricing-quiz"
    "pricing-v2"
    "privacy"
    "professional-reporting"
    "rd"
    "research-demo"
    "research-library"
    "research"
    "resources"
    "revenue-sharing"
    "risk-management"
    "robotic-automation"
    "security"
    "services"
    "signup"
    "sop-library"
    "support"
    "sustainability"
    "templates"
    "terms"
    "test-deploy"
    "test-minimal"
    "testimonials"
    "thd-compliance"
    "thermal-management"
    "track"
    "training"
    "troubleshoot"
    "ucc-filings"
    "unregister-sw"
    "vertical-farming-suite"
    "vertical-farming"
    "visual-operations"
    "water-analysis"
    "weather-ai"
    "workforce"
    "workplace-safety"
)

# Copy each directory
for dir in "${pages_to_copy[@]}"; do
    if [ -d "src-backup-app-full/$dir" ]; then
        echo "Copying $dir..."
        mkdir -p "src/app/$dir"
        cp -r "src-backup-app-full/$dir"/* "src/app/$dir/" 2>/dev/null || true
    fi
done

# Copy root files
echo "Copying root files..."
cp src-backup-app-full/error.tsx src/app/ 2>/dev/null || true
cp src-backup-app-full/global-error.tsx src/app/ 2>/dev/null || true
cp src-backup-app-full/not-found.tsx src/app/ 2>/dev/null || true
cp src-backup-app-full/sitemap.ts src/app/ 2>/dev/null || true

echo "Page restoration complete!"