#!/bin/bash

echo "Starting API route restoration..."

# List of API directories to copy
api_dirs=(
    "admin"
    "affiliate"
    "affiliates"
    "ai-assistant"
    "ai-design-chat"
    "ai-designer"
    "ai-interpret-data"
    "ai-status"
    "ai-test"
    "alerts"
    "analytics"
    "automation"
    "benchmarks"
    "cache"
    "changelog"
    "claude"
    "clear-forum-data"
    "compliance"
    "consolidation"
    "consultations"
    "costs"
    "credit"
    "cron"
    "data-import"
    "design"
    "disease-prediction"
    "emergency-stop"
    "energy-monitoring"
    "energy"
    "enterprise"
    "equipment-escrow"
    "equipment-matches"
    "equipment-offers"
    "equipment-requests"
    "equipment-verification"
    "equipment"
    "esg"
    "example-with-error-handling"
    "experts"
    "exports"
    "facilities"
    "food-safety"
    "forge"
    "gdpr"
    "integrations"
    "inventory"
    "investment"
    "investments"
    "ipm"
    "maintenance"
    "market-data"
    "marketplace"
    "metrics"
    "ml"
    "mobile"
    "monitoring"
    "notifications"
    "operations"
    "performance-guarantees"
    "photos"
    "ping"
    "proxy"
    "psi"
    "quality"
    "recordings"
    "reports"
    "revenue-sharing"
    "scouting"
    "sensors"
    "service-bids"
    "service-providers"
    "service-requests"
    "settings"
    "subscription"
    "system"
    "tasks"
    "test-claude"
    "test-openai"
    "test"
    "tracking"
    "troubleshoot"
    "upload"
    "user"
    "utility"
    "v2"
    "validation"
    "visual-ops"
    "water"
    "weather"
    "webhooks"
    "websocket"
    "work-orders"
    "workforce"
    "yield-prediction"
)

# Copy each API directory
for dir in "${api_dirs[@]}"; do
    if [ -d "src-backup-app-full/api/$dir" ]; then
        echo "Copying API route: $dir..."
        mkdir -p "src/app/api/$dir"
        cp -r "src-backup-app-full/api/$dir"/* "src/app/api/$dir/" 2>/dev/null || true
    fi
done

echo "API route restoration complete!"